/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package playquestion;

import static java.lang.Thread.sleep;
import javax.swing.ButtonGroup;
import java.util.*;




/**
 *
 * @author USER
 */
public class PQframe extends javax.swing.JFrame {
    /**
     * Creates new form PQframe
     */
   
    
    
    int score=0;
    static int milliseconds = 0;
    static int seconds = 30;
    static Boolean state = (true);
    
    Random num = new Random();
     int x = 0;  
   LinkedList<String> questions = new LinkedList<String>();
    LinkedList<String> optA = new LinkedList<String>();
     LinkedList<String> optB = new LinkedList<String>();
      LinkedList<String> optC = new LinkedList<String>();
       LinkedList<String> Ans = new LinkedList<String>();
        ButtonGroup g = new ButtonGroup();
        
   public void group(){
   g.add(optionA);
   g.add(optionB);
   g.add(optionC);
    }
    public void ClearBtns(){
   g.clearSelection();
   }
  
     public int getAnswer(){
            int sco=0;
  if(optionA.isSelected())
  {
    for(int z=0;z<=Ans.size()-1;z++)
    {
         if (optionA.getText().equalsIgnoreCase(Ans.get(z)))
            {
              score+=2;
                System.out.println(optionA.getText());
                 System.out.println(Ans.get(z));
               break;
            }  
    }    
       
  }  
  else if(optionB.isSelected())
  {
    for(int k=0;k<=Ans.size()-1;k++)
    {
         if (optionB.getText().equalsIgnoreCase(Ans.get(k)))
            {
                System.out.println(optionB.getText());
                 System.out.println(Ans.get(k));
               score+=2;
              break;
            }  
    }    
  }
  else if(optionC.isSelected())
  {
    for(int g=0;g<=Ans.size()-1;g++)
    {
         if (optionC.getText().equalsIgnoreCase(Ans.get(g)));
            {
                System.out.println(optionC.getText());
                 System.out.println(Ans.get(g));
                score+=2;
               break;
            }  
    }    
        
  }
   //else
  //{   
 // score+=0;   
 // }
  return score;
   }     
 
   
    
  
       
   public PQframe(){
        initComponents();
        group();
       
        
         
   
    
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp = new javax.swing.ButtonGroup();
        optionA = new javax.swing.JRadioButton();
        optionB = new javax.swing.JRadioButton();
        optionC = new javax.swing.JRadioButton();
        lblScore = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        lblquestion = new javax.swing.JLabel();
        btnstart = new javax.swing.JButton();
        millisecond = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 153, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);

        btngrp.add(optionA);
        optionA.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N

        btngrp.add(optionB);
        optionB.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        optionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBActionPerformed(evt);
            }
        });

        btngrp.add(optionC);
        optionC.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        optionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionCActionPerformed(evt);
            }
        });

        lblScore.setBackground(new java.awt.Color(0, 102, 102));
        lblScore.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTime.setBackground(new java.awt.Color(0, 102, 102));
        lblTime.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        lblTime.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("TIME");

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("SCORE");

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("PHYSICS");

        btnNext.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(0, 102, 102));
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblquestion.setBackground(new java.awt.Color(0, 102, 102));
        lblquestion.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        lblquestion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblquestion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Questions", 1, 0, new java.awt.Font("Maiandra GD", 3, 18), new java.awt.Color(255, 153, 51))); // NOI18N
        lblquestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnstart.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        btnstart.setForeground(new java.awt.Color(0, 102, 102));
        btnstart.setText("start");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });

        millisecond.setBackground(new java.awt.Color(0, 102, 102));
        millisecond.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Click Start to begin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(millisecond, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 614, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(210, 210, 210))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(234, 234, 234)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(optionC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(optionB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optionA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(millisecond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblquestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(optionA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(optionB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
        // TODO add your handling code here:
       
        
        
        process proc = new process();
        btnNext.setVisible(true);
        proc.add();
        proc.add_A();
        proc.add_B();
        proc.add_C();
        proc.add_Ans();
        proc.rand_Num();
        lblquestion.setText(proc.return_questions());
       
        optionA.setText(proc.return_optionA());
        optionB.setText(proc.return_optionB());
        optionC.setText(proc.return_optionC());
        
        
         
         Thread t;
        t = new Thread()
        {
            public void run ()
            { 
                for(;;)
                {
                    if (state == true)
                    {
                        try
                        {
                            sleep(1);
                            
                            if (milliseconds>1000)
                            {
                                milliseconds =0;
                                seconds--;
                            }
                               
                           
                             millisecond.setText(" : "+milliseconds);
                                 milliseconds++;
                                lblTime.setText(""+seconds);
                                
                                   if(seconds==0)
                              {
        proc.add();
        proc.add_A();
        proc.add_B();
        proc.add_C();
        proc.add_Ans();
        proc.rand_Num();
        lblquestion.setText(proc.return_questions());
        optionA.setText(proc.return_optionA());
        optionB.setText(proc.return_optionB());
        optionC.setText(proc.return_optionC());
       seconds=30;
                              state=true;
                           
                        }
                                 
                            }
                         
                        catch(Exception e)
                        {
                            
                        }
                    }
                        else
                        {
                        break;
                    }
                }}
        };
           t.start(); 
   
        btnstart.setVisible(false);   
        //ClearBtns();
    }//GEN-LAST:event_btnstartActionPerformed
        
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        
         seconds=30;
          process proc = new process();
        proc.add();
        proc.add_A();
        proc.add_B();
        proc.add_C();
        proc.add_Ans();
        proc.rand_Num();
        lblquestion.setText(proc.return_questions());
       
        optionA.setText(proc.return_optionA());
        optionB.setText(proc.return_optionB());
        optionC.setText(proc.return_optionC());
       btnNext.setVisible(true);
       lblScore.setText(String.valueOf(getAnswer()));
       ClearBtns();
       
      // System.out.print(getAnswer());
    }//GEN-LAST:event_btnNextActionPerformed

    private void optionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionBActionPerformed

    private void optionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PQframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PQframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PQframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PQframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PQframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup btngrp;
    private javax.swing.JButton btnstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblquestion;
    private javax.swing.JLabel millisecond;
    private javax.swing.JRadioButton optionA;
    private javax.swing.JRadioButton optionB;
    private javax.swing.JRadioButton optionC;
    // End of variables declaration//GEN-END:variables
}
